server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_ADDRESS}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    url: redis://${REDIS_USERNAME}:${REDIS_PASSWORD}@${REDIS_ADDRESS}
    timeout: 1000

cloud:
  env: ${CLOUD_ENV}
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.yourpackage.entity
  global-config:
    db-config:
      id-type: auto
      field-strategy: ignored
      column-format: '%s'

# Redisson configuration
redisson:
  address: ${REDIS_ADDRESS}
  database: 0
  codec: org.redisson.codec.JsonJacksonCodec
# JWT configuration
jwt:
  secret: naknfkaweLKAJKskqlLDJKLNdfadaf
  expiration: 3600